# Generated by Django 4.1.7 on 2023-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visiter_favitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiter',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
